FROM ruby:2.7

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y curl nodejs yarn vim git-core postgresql-client
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN mkdir /projects