version: "3"
services:
  db:
    image: postgres
  ruby:
    build: ./ruby
    ports:
      - 5911:3000
    volumes:
      - ./..:/projects
    depends_on:
      - db
    tty: true
    stdin_open: true